Controllers/BookController.cs
using liblib.Models;
using liblib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using liblib.Infrastructure.Services;

namespace liblib.Controllers
{
    [Authorize(Roles ="librarian")]
    public class BookController : Controller
    {

        private readonly IBookService bookService;
        public BookController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var books = bookService.Books();
            
            return View(books);
        }

        [HttpPost]
        public IActionResult Index(string searchString)
        {
            var books = this.bookService.Books();

            if (!String.IsNullOrEmpty(searchString))
            {
                string searchStringLow = searchString.ToLower();
                books = books.Where(s =>
                s.Name.ToLower().Contains(searchStringLow)
                || s.Author.ToLower().Contains(searchStringLow));
                return View(books);
            }
            return View("Index");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View("Add");
        }
    
        [HttpPost]
        public IActionResult Add(Book book)
        {
            if (book != null)
            {
                this.bookService.Add(book);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(String id)
        {
            this.bookService.Delete(id);
            return RedirectToAction("Index");
        }

        //public IActionResult EditPage()
        //{ return View("EditPage"); }

        [HttpGet]
        public ActionResult EditBook(String id)
        {

            Book book = this.bookService.Find(id);
            return View(book);

        }

        [HttpPost]
        public ActionResult EditBook(Book book)
        {
            this.bookService.Edit(book);
            return RedirectToAction("Index");
        }
    }
}

Controllers/OrdersController.cs
using liblib.Infrastructure.Services;
using liblib.Models;
using liblib.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace liblib.Controllers
{
    [Authorize(Roles = "librarian")]
    public class OrdersController : Controller
    {
        private readonly IBookService bookService;
        private readonly IUserService userService;
        private readonly IOrderService orderService;
        private readonly UserManager<IdentityUser> userManager;
        private readonly LiblibContext db;
        public OrdersController(IBookService bookService, IUserService userService, IOrderService orderService, UserManager<IdentityUser> userManager, LiblibContext db)
        {
            this.userService = userService;
            this.bookService = bookService;
            this.orderService = orderService;
            this.userManager = userManager;
            this.db = db;
        }
        public IActionResult Index()
        {
            var orders = orderService.Orders();

            return View(orders);
        }
        public IActionResult GiveOut(string id)
        {
            if (id != null)
            {
                this.orderService.SetTimeBookWasGiven(id);
            }
            return RedirectToAction("Index");
        }
        public IActionResult TakeBack(string id)
        {
            if (id != null)
            {
                var orders = orderService.Orders();
                this.orderService.CancelOrder(id);
                var order = orders.Where(o => o.Id==id).Single();
                var book = order.Book;
                book.Quantity++;
                bookService.Edit(book);

            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> SendMessage(string id)
        {
            var orders = orderService.Orders();
            var order = orders.Where(i => i.Id==id).Single();
            EmailService emailService = new EmailService();
            await emailService.SendEmailAsync(order.User.Email, "Напоминание!", "В соответствии с правилами библиотеки необходимо вернуть книгу" + order.DateBookToReturn);
            return RedirectToAction("Index");
        }
    }
}

Controllers/RolesController.cs
using liblib.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace liblib.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        readonly RoleManager<IdentityRole> _roleManager;
        readonly UserManager<IdentityUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
               await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new()
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library Booking Service</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole("librarian"))
                        {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Librarian Tools</a>
                    </li>
                        }
                                    @if (User.IsInRole("librarian"))
                                    {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders List</a>
                    </li>}
                                                    @if (User.IsInRole("admin"))
                                                    {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Users and Roles</a>
                                    </li>}
                                                                </ul>
                    <partial name="/Views/Shared/_LoginPartial.cshtml" />
                </div>
            </div>


        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - liblib - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>